apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  labels:
    app.kubernetes.io/name: jaeger-query
    owner: platformsredev
    infra.arc/repo.managed: kubernetes
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-query
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger-query
        owner: platformsredev
        infra.arc/repo.managed: kubernetes
    spec:
      containers:
      - command:
          - "/go/bin/query-linux"
          #- "--es.server-urls=http://localhost:9200"
          - "--es.server-urls=http://elasticsearch.default.svc.cluster.local:9200/"
          - "--es.tls.enabled=false"
          #- "--es.usePassword=false"
          - "--es.username="
          - "--span-storage.type=elasticsearch"
          - "--log-level=debug"
        env:
          - name: SPAN_STORAGE_TYPE
            value: "elasticsearch"
          - name: JAEGER_DISABLED
            value: "false"
          - name: JAEGER_ENDPOINT
            value: "http://jaeger-collector.default.svc.cluster.local:14268/api/traces"
        image: jaegertracing/jaeger-query:1.21
        name: jaeger-query
        ports:
        - containerPort: 16686
