apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-nginx
    labels:
        type: frontend
spec:
    selector:
        matchLabels:
            type: frontend
    template:
        metadata:
            labels:
                type: frontend
        spec:
            containers:
            - name: nginx
              image: nginx:1.14.2
              env:
              - name: SECRET_USERNAME
                valueFrom:
                    secretKeyRef:
                        name: test-secret
                        key: username
              - name: SECRET_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: test-secret
                        key: password
              volumeMounts:
                - name: secret-volume
                  mountPath: /etc/secret-dir
            topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: node
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                    type: frontend
            - maxSkew: 1
              topologyKey: zone
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                    type: frontend
            
            volumes:
            - name: secret-volume
              secret:
                secretName: test-secret
