apiVersion: v1
kind: Service
metadata:
    name: my-nginx-svc
    labels:
        type: frontend
spec:
    type: NodePort
    selector:
        type: frontend
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
