apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-redis-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-redis
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 5
