apiVersion: v1
kind: Service
metadata:
    name: my-redis-svc
    labels:
        type: frontend
spec:
    type: ClusterIP
    selector:
        type: frontend
    ports:
        - protocol: TCP
          port: 81
          targetPort: 6379
